### ISSUE TITLE
[FEATURE] 댓글 컴포넌트 작성 & API 연결

### ISSUE THREAD

**Issue by bongsh0112** [hook-killer/front-end#35]
# 🤖 기능 개요

게시글에 달 댓글 컴포넌트를 만들고 API 를 연결합니다

### ✅ Implement TODO

- [x] Reply 컴포넌트 작성
- [x] API 만들어 서버와 통신 되는지 확인

**Comment by donsonioc2010** [comment]
기능구현 완료로 인한 Issue Close
