### ISSUE TITLE
게시판 수정 이슈 2

### ISSUE THREAD

**Issue by lljh1992** [hook-killer/front-end#66]
타인 작성 글도 수정 버튼 클릭 ->  내용 업데이트 수정완료 모달 출력 -> 업데이트는 안됨

**Comment by donsonioc2010** [comment]
Detail페이지에서 버튼 안보이도록 완료. 업데이트 링크로는 들어갈 수 있는데 귀찮귀찮~

**Comment by donsonioc2010** [comment]
Issue 처리 완료하여 Issue Close
