### ISSUE TITLE
로그아웃 이슈 (내용)

### ISSUE THREAD

**Issue by lljh1992** [hook-killer/front-end#67]
오른쪽 상단 메뉴 -> 로그아웃 -> 새로고침 -> 메뉴 -> 로그아웃 버튼이 유지됨 

버튼만 유지되는걸로 파악됨 마이페이지에 유저가 넘어오지는 않음

오른쪽 상단메뉴 -> 로그아웃 -> 로그인 -> 로그인페이지로 잘넘어가짐

새로고침 하면 로그아웃 버튼이 유지가 되는거 같음

**Comment by donsonioc2010** [comment]
이거 오탈자문제같습니다.
ROLE이 GUEST인 경우 로그인버튼페이지를 뜨게하였는데, 기본Role이 GEUST더라구요..

추후 확인필요합니당.

**Comment by lljh1992** [comment]
현재 기준 로그아웃 유지 되는 현상 해결로 확인됨 

다른 이슈 발생

로그인 -> 새로고침 -> 메뉴옆에 undefined 뜸

**Comment by lljh1992** [comment]
완료
